### PR TITLE
Updated sub regions (AS923_1C+, AU915_SB1, EU868_B+)

### LINKED ISSUE #118: Add AS923_1C plan when available
Helium are adding an AS923_1C plan.

Screenshot_20230123_002848_Discord
Screenshot_20230123_002906_Discord

Link: https://discord.com/channels/404106811252408320/813452716286017557/1062114939684278382

### PR DESCRIPTION
**Pull request by MuratUrsavas**
**Issue**
(https://nebraltd.atlassian.net/browse/NEBD-71) (Closes #118)

New sub region plans has been added. Some of the existing ones has been updated with notes.

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Review by pritamghanghas — APPROVED** [review]
why is it showing so many new files. Did they create so many new profiles.

**Comment by MuratUrsavas** [comment]
@pritamghanghas Yep!

**Comment by shawaj** [comment]
@MuratUrsavas we need to remove all the comments from the JSON files or it will break things.

We ran into this issue before... ref https://github.com/NebraLtd/hm-pktfwd/pull/106

**Comment by shawaj** [comment]
Also @MuratUrsavas you need to add them to here https://github.com/NebraLtd/hm-pktfwd/blob/master/pktfwd/config/region_config_filenames.py

**Comment by MuratUrsavas** [comment]
@shawaj Thanks for pointing them out.

**Comment by MuratUrsavas** [comment]
Done with #139

**Pull request merged**
