### PR TITLE
fix: copy configs to correct locations

### PR DESCRIPTION
**Pull request by shawaj**
**Why**

fix: copy configs to correct locations

**How**

- copy sx1302 config to correct location
- copy local_conf.json to correct place for sx1302 and sx1301
- add more logging and notes

**References**

Relates-to: #70
Relates-to: #72

### CODE REVIEW

**Comment by shawaj** [comment]
Should be merged at same time as #72

**Review by marvinmarnold — APPROVED** [review]
Nice work. I wonder if it would be less complex, if we updated all of the `global_conf.json`s to include the missing information from `local_config.json`.

```
{
    "gateway_conf": {
	        "servers": [
            {
                "serv_type": "semtech",
                "server_address": "helium-miner",
                "serv_port_up": 1680,
                "serv_port_down": 1680,
                "serv_enabled": true
	    }
	],
	"gps": false,
  "fake_gps": true,
  "ref_latitude": 0,
  "ref_longitude": 0,
  "ref_altitude": 0
    }
}
```
That would be consistent with how the sx1301 [local_conf](https://github.com/NebraLtd/hm-pktfwd/blob/e067bef1be17f9d3c1036cbe1100b317d5cc5f57/pktfwd/config/lora_templates_sx1301/local_conf.json) is already present in the regional [global_confs](https://github.com/NebraLtd/hm-pktfwd/blob/e067bef1be17f9d3c1036cbe1100b317d5cc5f57/pktfwd/config/lora_templates_sx1301/US-global_conf.json#L197). 

The sx1302 lora_pktfwd has the [same behavior](https://github.com/NebraLtd/sx1302_hal/blob/9a72ce59c22b0434bdbaf9091542a7d8419bddee/packet_forwarder/src/lora_pkt_fwd.c#L1535) of loading global_conf first then overwriting with local_conf if present.

**Comment by shawaj** [comment]
@marvinmarnold yeah maybe that's a better way to do it - just have the single config.

I'm trying to think if there is any particular reason / scenario in which we would want to use a local_conf.json

The only thing I can think of is optionally adding features like GPS based on whether there is a GPS module available for example. But I guess we could always do that like we are doing with SPI bus by injecting JSON objects

**Comment by marvinmarnold** [comment]
> I'm trying to think if there is any particular reason / scenario in which we would want to use a local_conf.json
> 
> (And I guess we can always add in local_conf.json stuff later if we change our minds)

@shawaj I don't have a strong opinion, there are merits of both ways. This method is already complete, which is always a +1.

**Comment by shawaj** [comment]
@marvinmarnold let's leave it as is now then. The one benefit to having the local_conf.json I guess is that we can override those parameters without editing every regional file, for example

**Pull request merged**
