### PR TITLE
Revert to direct to Helium miner for now.

### PR DESCRIPTION
**Pull request by robputt**
**Issue**

- Link:
- Summary:

**How**

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Review by KevinWassermann94 — APPROVED** [review]

**Review by ilyastrodubtsev — APPROVED** [review]

**Comment by robputt** [comment]
> @robputt what's the purpose of this? Something not working?

Apparently after some time hotspots stop forwarding packets from the multiplexer to the helium miner and they just blat out UDP error to the log. I am investigating but for now reverting. I think it hasn't been seen on my dev device because it doesn't stay online long enough without code pushes to see these affects. I'll try and get a fix in and deployed to the dev device before the weekend as I am away and then see if it's in this state when I get back :-).

**Comment by shawaj** [comment]
Oh ok, interesting. I did notice something similar but didn't realise it was all packets falling.

By the way, does the port need to change to something different?

**Comment by shawaj** [comment]
1680 isn't it @robputt ?

**Comment by robputt** [comment]
> Oh ok, interesting. I did notice something similar but didn't realise it was all packets falling.
> 
> By the way, does the port need to change to something different?

Nah port is unrelated. They are already using non conflicti

> 1680 isn't it @robputt ?

shit, you right... let me raise another PR.

**Comment by robputt** [comment]
@shawaj https://github.com/NebraLtd/hm-pktfwd/pull/128

**Pull request merged**
